out_dir: results
metric_best: auc
wandb:
  use: True
  project: molsider
dataset:
  format: OGB
  name: ogbg-molsider
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 8
  model: DeepSet
  dim_pe: 8
  layers: 2
  n_heads: 4  # Only used when `posenc.model: Transformer`
  raw_norm_type: none
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: SupernetModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Transformer
  layers: 10
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.05
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph_multi
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0001
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 1e-5
#  base_lr: 0.0001
#  max_epoch: 100
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 5
#  min_lr: 1e-6
nas:
  test: False
  experiment_name: ogbg-molsider-os
  enable: True # if False, just train the supernet model
  supernet_layer_types: [['GCN', 'GAT', 'GINE', 'GENConv'], ['Transformer', 'Performer']]
  layer_num: 5
  parallel_num: 1 
  encoder:
    enable: False # if False, won't search for encoder
    fixed_types: ['TypeDictNode']
    variable_types: ['LapPE', 'RWSE']
  algorithm: one_shot
  any_shot:
    supernet_max_epoch: 50
    sub_supernet_max_epoch: 0
    retrain_search_max_epoch: 0
    retrain_best_max_epoch: 200
    split_num: 2
    retrain_top_k: 5
  search_algorithm: GA
  ga:
    max_generations: 5
    population_size: 30
    mutation_rate: 0.1
    crossover_rate: 0.6
accelerator: cuda:0